export const items = [
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة أفطار",
		description: "وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة وجبة أفطار متكاملة",
		price: "50 جنية",
		image: "../public/img/breakfast.png",
		category: "افطار",
	},
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
	{
		id: Math.random(),
		title: "وجبة غداء",
		description: "وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة وجبة غداء متكاملة",
		price: "50 جنية",
		image: "../public/img/dinner.png",
		category: "غداء",
	},
];
